<?php
declare(strict_types=1);

if (PHP_SAPI !== 'cli') { http_response_code(403); exit("CLI only\n"); }
$config=require dirname(__DIR__).'/config.php';require dirname(__DIR__).'/src/Database.php';
$path=$argv[1]??dirname(__DIR__).'/storage/imports/PaperbellDataMap.json';
$rows=json_decode((string)file_get_contents($path),true,512,JSON_THROW_ON_ERROR);
if(count($rows)<2)throw new RuntimeException('Data mapping kosong.');
$headers=array_map(fn($v)=>trim((string)$v),array_shift($rows));$idx=array_flip($headers);$db=Database::mysql($config['mysql']);$now=time();
function val(array $r,array $i,string $k):string{return trim((string)($r[$i[$k]??-1]??''));}
function valAny(array $r,array $i,array $keys):string{foreach($keys as $key){$value=val($r,$i,$key);if($value!=='')return$value;}return'';}
function norm(string $s):string{return strtolower(str_replace(' ','',trim($s)));}
function pages(mixed $raw):array{if(is_numeric($raw)&&((float)$raw)>500){$days=(int)$raw;$date=(new DateTimeImmutable('1899-12-30',new DateTimeZone('UTC')))->modify("+{$days} days");$a=(int)$date->format('n');$b=(int)$date->format('j');return [min($a,$b),max($a,$b)];}$s=trim((string)$raw);if(preg_match('/^(\d+)?\s*(?:-\s*(\d+)?)?$/',$s,$m)){ $from=max(1,(int)($m[1]??1));if(!str_contains($s,'-'))return[$from,$from];$to=isset($m[2])&&$m[2]!==''?(int)$m[2]:0;return[$from,$to];}return[1,1];}
$db->beginTransaction();try{$db->exec('DELETE FROM mapping_aliases; DELETE FROM data_mappings;');$insert=$db->prepare('INSERT INTO data_mappings(sku_id,product_name,variation_name,group_name,product_code,variant_1,variant_2,duplex,paper,page_from,page_to,copies,file_path,parent_sku,variation,printer,search_product,search_variant,search_alias,imported_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$alias=$db->prepare('INSERT IGNORE INTO mapping_aliases(alias_key,mapping_id) VALUES(?,?)');$count=0;$aliasCount=0;foreach($rows as $r){$sku=val($r,$idx,'SKU ID');if($sku==='')continue;[$from,$to]=pages($r[$idx['Page']]??'');$parent=valAny($r,$idx,['SKU Inti','SKU Induk','Parent SKU']);$productCode=val($r,$idx,'Product Code');$v1=val($r,$idx,'Variant-1');$v2=val($r,$idx,'Variant-2');$duplex=val($r,$idx,'Duplex');$paper=val($r,$idx,'Size');$insert->execute([$sku,val($r,$idx,'Nama Produk'),val($r,$idx,'Nama Variasi'),val($r,$idx,'Group'),$productCode,$v1,$v2,$duplex,$paper,$from,$to,max(1,(int)val($r,$idx,'Copies')),val($r,$idx,'File Path'),$parent,val($r,$idx,'Variasi'),val($r,$idx,'Printer Name'),val($r,$idx,'Search Product'),val($r,$idx,'Search Variant'),val($r,$idx,'Search Alias'),$now]);$id=(int)$db->lastInsertId();$keys=[norm($sku.$parent),norm($parent),norm($sku),norm(($v1.$v2.$paper).($duplex.$productCode)),norm($parent.$sku)];foreach(array_unique(array_filter($keys)) as $key){$alias->execute([$key,$id]);$aliasCount+=$alias->rowCount();}$count++;}$db->commit();foreach(['order-mapping-cache.json','order-file-availability-cache.json'] as $file)@unlink(dirname(__DIR__).'/storage/'.$file);echo "Imported {$count} mappings, {$aliasCount} aliases.\n";}catch(Throwable $e){if($db->inTransaction())$db->rollBack();throw $e;}
