<?php
declare(strict_types=1);

final class MarketplaceOrderSyncService
{
    public function __construct(private PDO $db,private MarketplaceOAuthService $oauth){$this->ensureSchema();}

    private function ensureSchema(): void
    {
        $this->db->exec("CREATE TABLE IF NOT EXISTS sync_runs(id BIGINT AUTO_INCREMENT PRIMARY KEY,provider VARCHAR(30) NOT NULL,status VARCHAR(30) NOT NULL,orders_count INT NOT NULL DEFAULT 0,message TEXT NOT NULL,created_by VARCHAR(100) NOT NULL DEFAULT '',started_at BIGINT NOT NULL,completed_at BIGINT NULL,INDEX ix_sync_runs_started(started_at)) ENGINE=InnoDB");
        $legacyNote=$this->db->query("SHOW COLUMNS FROM orders LIKE 'internal_note'")->fetch();
        if($legacyNote&&strtoupper((string)($legacyNote['Null']??''))==='NO')$this->db->exec("ALTER TABLE orders MODIFY COLUMN internal_note TEXT NULL DEFAULT NULL");
    }

    public function sync(string $provider,string $user): array
    {
        if(!in_array($provider,['shopee','tiktok'],true))throw new InvalidArgumentException('Provider sync tidak didukung.');
        $lock='paperbell_sync_'.$provider;if((int)$this->db->query("SELECT GET_LOCK(".$this->db->quote($lock).",0)")->fetchColumn()!==1)throw new RuntimeException('Sync '.$provider.' sedang berjalan.');
        $run=$this->db->prepare("INSERT INTO sync_runs(provider,status,message,created_by,started_at) VALUES(?,'processing','Mengambil order langsung dari marketplace',?,?)");$run->execute([$provider,$user,time()]);$id=(int)$this->db->lastInsertId();
        try{$stats=$provider==='shopee'?$this->syncShopee():$this->syncTikTok();$message=sprintf('Sync selesai: %d diperiksa, %d baru, %d minta cancel',$stats['orders'],$stats['new_orders'],count($stats['cancel_requests']));$this->db->prepare("UPDATE sync_runs SET status='completed',orders_count=?,message=?,completed_at=? WHERE id=?")->execute([$stats['orders'],$message,time(),$id]);$this->meta('last_sync_at',(string)time());$this->meta('last_'.$provider.'_sync_at',(string)time());return array_merge(['ok'=>true,'id'=>$id,'provider'=>$provider],$stats);}
        catch(Throwable $e){$this->db->prepare("UPDATE sync_runs SET status='failed',message=?,completed_at=? WHERE id=?")->execute([mb_substr($e->getMessage(),0,1500),time(),$id]);throw $e;}
        finally{$this->db->query("SELECT RELEASE_LOCK(".$this->db->quote($lock).")");}
    }

    private function syncShopee(): array
    {
        $auth=$this->oauth->credentials('shopee');$cfg=$auth['config'];$token=(string)$auth['access_token'];$shop=(string)$auth['account_id'];$to=time();$from=$to-7*86400;$sns=[];
        foreach(['PROCESSED','READY_TO_SHIP','IN_CANCEL','CANCELLED'] as $status){$cursor='';$pages=0;do{$q=['time_range_field'=>'update_time','time_from'=>$from,'time_to'=>$to,'page_size'=>50,'order_status'=>$status];if($cursor!=='')$q['cursor']=$cursor;$json=$this->shopeeGet('/api/v2/order/get_order_list',$q,$cfg,$token,$shop);$this->shopeeOk($json);$response=$json['response']??[];foreach(($response['order_list']??[]) as $row)if(!empty($row['order_sn']))$sns[(string)$row['order_sn']]=true;$cursor=!empty($response['more'])?(string)($response['next_cursor']??''):'';$pages++;}while($cursor!==''&&$pages<30);}
        $existing=$this->existingStatuses(array_keys($sns));$count=0;$new=0;$cancelRequests=[];foreach(array_chunk(array_keys($sns),50) as $batch){$json=$this->shopeeGet('/api/v2/order/get_order_detail',['order_sn_list'=>implode(',',$batch),'response_optional_fields'=>'order_status,create_time,update_time,total_amount,item_list,buyer_username,note,note_update_time,package_list'],$cfg,$token,$shop);$this->shopeeOk($json);foreach(($json['response']['order_list']??[]) as $order){$sn=(string)($order['order_sn']??'');$status=strtoupper((string)($order['order_status']??''));$oldStatus=strtoupper((string)($existing[$sn]??''));if($sn!==''&&!array_key_exists($sn,$existing))$new++;if($sn!==''&&$this->isCancellationRequest($status)&&!$this->isCancellationRequest($oldStatus))$cancelRequests[]=$sn;$this->upsertShopee($order);$count++;}}
        return['orders'=>$count,'new_orders'=>$new,'cancel_requests'=>array_values(array_unique($cancelRequests))];
    }

    private function syncTikTok(): array
    {
        $auth=$this->oauth->credentials('tiktok');$cfg=$auth['config'];$token=(string)$auth['access_token'];$secret=(string)($cfg['app_secret']??'');$app=(string)($cfg['app_key']??'');$cipher=(string)($cfg['shop_cipher']??'');if($cipher==='')throw new RuntimeException('Shop cipher TikTok belum dikonfigurasi.');
        $to=time();$from=$to-7*86400;$ids=[];$pageToken='';$pages=0;do{$query=['page_size'=>'50','sort_field'=>'update_time','sort_order'=>'DESC'];if($pageToken!=='')$query['page_token']=$pageToken;$json=$this->tiktok('POST','/order/202309/orders/search',$query,['update_time_ge'=>$from,'update_time_lt'=>$to],$app,$secret,$cipher,$token);foreach(($json['data']['orders']??[]) as $order){$id=(string)($order['id']??$order['order_id']??'');if($id!=='')$ids[$id]=true;}$pageToken=(string)($json['data']['next_page_token']??'');$pages++;}while($pageToken!==''&&$pages<100);
        $existing=$this->existingStatuses(array_map(fn($id)=>'TIKTOK:'.$id,array_keys($ids)));$count=0;$new=0;$cancelRequests=[];foreach(array_chunk(array_keys($ids),50) as $batch){$json=$this->tiktok('GET','/order/202507/orders',['ids'=>implode(',',$batch)],null,$app,$secret,$cipher,$token);foreach(($json['data']['orders']??[]) as $order){$id=(string)($order['id']??$order['order_id']??'');$sn='TIKTOK:'.$id;$status=strtoupper((string)($order['status']??''));$oldStatus=strtoupper((string)($existing[$sn]??''));if(in_array($status,['UNPAID','UN_PAID','PENDING_PAYMENT','PAYMENT_PENDING'],true))continue;if($id!==''&&!array_key_exists($sn,$existing))$new++;if($id!==''&&$this->isCancellationRequest($status)&&!$this->isCancellationRequest($oldStatus))$cancelRequests[]=$sn;$this->upsertTikTok($order);$count++;}}
        return['orders'=>$count,'new_orders'=>$new,'cancel_requests'=>array_values(array_unique($cancelRequests))];
    }

    private function upsertShopee(array $order): void
    {
        $sn=(string)($order['order_sn']??'');if($sn==='')return;$status=(string)($order['order_status']??'');$create=(int)($order['create_time']??0);$update=(int)($order['update_time']??0);$buyer=(string)($order['buyer_username']??'');$this->upsertOrder($sn,$status,$create,$update,$buyer,$order);$lineIds=[];$i=0;
        foreach(($order['item_list']??[]) as $item){$itemSku=strtoupper(str_replace(' ','',trim((string)($item['item_sku']??''))));$modelSku=strtoupper(str_replace(' ','',trim((string)($item['model_sku']??$item['variation_sku']??''))));$itemId=(string)($item['item_id']??'');$modelId=(string)($item['model_id']??'');$lineId=$modelId!==''&&$modelId!=='0'?$itemId.':'.$modelId:(string)($item['order_item_id']??$itemId.':'.$i);$i++;$lineIds[]=$lineId;$this->upsertLine($sn,$lineId,$itemSku.$modelSku,$modelSku,$itemSku,(string)($item['item_name']??''),(string)($item['model_name']??''),max(1,(int)($item['model_quantity_purchased']??1)),$status,$create);}
        $this->deleteStaleLines($sn,$lineIds);
    }

    private function upsertTikTok(array $order): void
    {
        $id=(string)($order['id']??$order['order_id']??'');if($id==='')return;$sn='TIKTOK:'.$id;$status=(string)($order['status']??'');$create=(int)($order['create_time']??0);$update=(int)($order['update_time']??0);$recipient=(string)($order['recipient_address']['name']??'');$userId=(string)($order['user_id']??'');$buyer=$recipient!==''&&$userId!==''?$recipient.' ('.$userId.')':($userId?:$recipient);$this->upsertOrder($sn,$status,$create,$update,$buyer,$order);$this->upsertTrackingNumber($sn,$this->findFirst($order,['tracking_number','trackingNumber','tracking_id','trackingId','waybill_number','waybillNumber']));$lineIds=[];$i=0;
        foreach(($order['line_items']??[]) as $item){$lineId=(string)($item['id']??$item['line_item_id']??$item['sku_id']??'line:'.$i);$i++;$lineIds[]=$lineId;$sellerSku=trim((string)($item['seller_sku']??''));$skuId=(string)($item['sku_id']??'');$productId=(string)($item['product_id']??'');$itemKey=$sellerSku!==''?$sellerSku:($skuId?:$productId);$qty=max(1,(int)($item['quantity']??$item['qty']??1));$this->upsertLine($sn,$lineId,$itemKey,'',$sellerSku,(string)($item['product_name']??''),(string)($item['sku_name']??''),$qty,$status,$create);}
        $this->deleteStaleLines($sn,$lineIds);
    }

    private function upsertOrder(string $sn,string $status,int $create,int $update,string $buyer,array $raw): void{$stmt=$this->db->prepare('INSERT INTO orders(order_sn,status,create_time,update_time,buyer_username,raw_json) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE status=VALUES(status),create_time=VALUES(create_time),update_time=VALUES(update_time),buyer_username=VALUES(buyer_username),raw_json=VALUES(raw_json)');$stmt->execute([$sn,$status,$create,$update,$buyer,json_encode($raw,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);}
    private function existingStatuses(array $sns): array{if(!$sns)return[];$found=[];foreach(array_chunk(array_values(array_unique($sns)),200) as $batch){$marks=implode(',',array_fill(0,count($batch),'?'));$stmt=$this->db->prepare("SELECT order_sn,status FROM orders WHERE order_sn IN ($marks)");$stmt->execute($batch);foreach($stmt->fetchAll() as $row)$found[(string)$row['order_sn']]=(string)$row['status'];}return$found;}
    private function isCancellationRequest(string $status): bool{return str_contains($status,'CANCEL')&&!in_array($status,['CANCELLED','CANCELED'],true);}
    private function upsertLine(string $sn,string $lineId,string $itemKey,string $modelSku,string $itemSku,string $itemName,string $modelName,int $qty,string $status,int $create): void{$stmt=$this->db->prepare('INSERT INTO order_process(order_sn,order_item_id,item_key,model_sku,item_sku,item_name,model_name,qty,status,create_time,saved_at) VALUES(?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE item_key=VALUES(item_key),model_sku=VALUES(model_sku),item_sku=VALUES(item_sku),item_name=VALUES(item_name),model_name=VALUES(model_name),qty=VALUES(qty),status=VALUES(status),create_time=VALUES(create_time),saved_at=VALUES(saved_at)');$stmt->execute([$sn,$lineId,$itemKey,$modelSku,$itemSku,$itemName,$modelName,$qty,$status,$create,time()]);}
    private function deleteStaleLines(string $sn,array $ids): void{if(!$ids)return;$marks=implode(',',array_fill(0,count($ids),'?'));$stmt=$this->db->prepare("DELETE FROM order_process WHERE order_sn=? AND order_item_id NOT IN ($marks)");$stmt->execute(array_merge([$sn],$ids));}
    private function upsertTrackingNumber(string $sn,string $tracking): void{if($tracking==='')return;$stmt=$this->db->prepare("INSERT INTO order_resi(order_sn,pdf_path,tracking_number) VALUES(?,'',?) ON DUPLICATE KEY UPDATE tracking_number=VALUES(tracking_number)");$stmt->execute([$sn,$tracking]);}
    private function findFirst(mixed $value,array $keys): string{if(!is_array($value))return'';foreach($keys as $key)if(isset($value[$key])&&(is_string($value[$key])||is_numeric($value[$key]))&&trim((string)$value[$key])!=='')return trim((string)$value[$key]);foreach($value as $child)if(is_array($child)&&($found=$this->findFirst($child,$keys))!=='')return$found;return'';}

    private function shopeeGet(string $path,array $extra,array $cfg,string $token,string $shop): array{$ts=time();$partner=(string)($cfg['partner_id']??'');$q=array_merge(['partner_id'=>$partner,'timestamp'=>$ts,'sign'=>hash_hmac('sha256',$partner.$path.$ts.$token.$shop,(string)($cfg['partner_key']??'')),'access_token'=>$token,'shop_id'=>$shop],$extra);return$this->json('GET',rtrim((string)($cfg['api_host']??'https://partner.shopeemobile.com'),'/').$path.'?'.http_build_query($q,'','&',PHP_QUERY_RFC3986),[],null);}
    private function shopeeOk(array $json): void{$e=(string)($json['error']??'');if($e!==''&&$e!=='0')throw new RuntimeException('Shopee API: '.($json['message']??$e).' ['.$e.']');}
    private function tiktok(string $method,string $path,array $query,?array $body,string $app,string $secret,string $cipher,string $token): array{$query['app_key']=$app;$query['shop_cipher']=$cipher;$query['timestamp']=(string)time();ksort($query,SORT_STRING);$bodyText=$body===null?'':json_encode($body,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR);$source=$path;foreach($query as $k=>$v)$source.=$k.$v;$source.=$bodyText;$query['sign']=hash_hmac('sha256',$secret.$source.$secret,$secret);$json=$this->json($method,'https://open-api.tiktokglobalshop.com'.$path.'?'.http_build_query($query,'','&',PHP_QUERY_RFC3986),['Content-Type: application/json','x-tts-access-token: '.$token],$bodyText===''?null:$bodyText);if((int)($json['code']??-1)!==0)throw new RuntimeException('TikTok API '.($json['code']??'?').': '.($json['message']??'unknown error'));return$json;}
    private function json(string $method,string $url,array $headers,?string $body): array{$ch=curl_init($url);curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CONNECTTIMEOUT=>10,CURLOPT_TIMEOUT=>45,CURLOPT_FOLLOWLOCATION=>false,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$headers]);if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,$body);$raw=curl_exec($ch);$status=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);$error=curl_error($ch);curl_close($ch);if($raw===false)throw new RuntimeException('Koneksi sync gagal: '.$error);$json=json_decode($raw,true);if(!is_array($json))throw new RuntimeException('Respons sync bukan JSON valid.');if($status<200||$status>=300)throw new RuntimeException('Marketplace HTTP '.$status.': '.($json['message']??$json['error']??'rejected'));return$json;}
    private function meta(string $key,string $value): void{$stmt=$this->db->prepare('INSERT INTO app_meta(meta_key,meta_value) VALUES(?,?) ON DUPLICATE KEY UPDATE meta_value=VALUES(meta_value)');$stmt->execute([$key,$value]);}
}
